server.port: 10000

stripe:
  public.key: placeholder
  secret.key: placeholder

exchange:
  rate:
    api:
      url: ${EXCHANGE_RATE_API_URL:https://open.er-api.com/v6/latest/}
      timeout: 5000
    cache:
        ttl:
          minutes: 30

spring:
  data.mongodb:
    uri: placeholder
    database: placeholder

  mail:
    host: smtp.gmail.com
    port: 587
    username: placeholder
    password: placeholder
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

email:
  notification:
    enabled: true

app:
  frontend-url: http://localhost:4200

jwt:
  cookieName: placeholder
  cookieSameSite: ${JWT_COOKIE_SAME_SITE:Lax}
  cookieSecure: ${JWT_COOKIE_SECURE:false}
  secret: placeholder
  expirationMs: 86400000

cors:
  allowed-origins: http://localhost:4200

cancelUrl: 'http://localhost:4200/#/payment-failed'
successUrl: 'http://localhost:4200/#/success'

admin.seed.emails: email1, email2
admin.seed.sync-user-roles: true