name: Render Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Send keep-alive HTTP request
        run: |
          curl -s https://rungika-server.onrender.com/swagger-ui/index.html || true